### ISSUE TITLE
Some thoughts

### ISSUE THREAD

**Issue by schwehr** [stac-extensions/themes#1]
This is my comment on https://gitter.im/SpatioTemporal-Asset-Catalog/Lobby?at=62b41f1a568c2c30d3dfa48b

It seems like there should be an explanation of how this relates to the existing keywords field and how it relate to other ontology schemes. I've been wanting to have a glossary type section parallel to an existing catalog that has a STAC Catalog for each keyword that explains the keyword and links to all the STAC Collections / Items that have that keyword (the Earth Engine catalog is currently completely static). How might that idea relate?

**Comment by schwehr** [comment]
https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md#collection-fields

Existing keywords:

|Element | Type | Description
|-- | -- | --
| keywords | [string] | List of keywords describing the Collection.|

**Comment by emmanuelmathot** [comment]
ok I see the ambiguity here. The idea is to have a space for free keywords without any reference. Pretty much as tags. Terms are bond to a reference system.
Initially, there are no links intended here between the 2 fields. I'd like a system easy to implement and quick for searching in STAC API.
I think there are enough ontology reference system to tap into but we could imagine the reference system pointing to a local existing catalog.

**Comment by m-mohr** [comment]
I'm still a bit confused.

You said:

> The idea is to have a space for free keywords without any reference. Pretty much as tags.

This is exactly the purpose of the STAC Collection `keywords` field. How it the keywords fieldhere and in the Collection different? And if they are different (which I assume), I think it would make sense to use another field name to make the difference clearer.

What I'm also wondering about is whether you could re-use `keywords` and just add the terms on top?

**Comment by emmanuelmathot** [comment]
Actually no differences with the field `keywords` of a collection except they apply to an item. We could extend the keyword field for the items.
Nevertheless, the core of this extension is about system referenced terms with the field `subjects:terms`.

**Comment by m-mohr** [comment]
Yes, I think that is a good idea and would be very much in line with the common metadata model STAC is embracing. So generalize keywords for Items and Collections and then extend it.
In that case, it might make sense to call the terms field something like "keyword:terms"?

**Comment by emmanuelmathot** [comment]
Indeed, it could. So could we keep it as an extension or make it part of the core spec?

**Comment by m-mohr** [comment]
They keyword list should be core spec, i.e. common metadata: https://github.com/radiantearth/stac-spec/blob/master/item-spec/common-metadata.md This is likely just a copy/paste from the Collection spec.

And then the separate extension would basically be the terms. But this is just my opinion right now.

**Comment by jjrom** [comment]
I agree with @m-mohr on the keywords for items. It should be in the core spec as a copy/paste from the collection spec i.e. a field named `keywords`

**Comment by schwehr** [comment]
Reading up on [RDF](https://en.wikipedia.org/wiki/Resource_Description_Framework) and [OWL2](https://en.wikipedia.org/wiki/Web_Ontology_Language) was pretty frustrating.

This looks interesting: https://www.earthdata.nasa.gov/learn/find-data/idn/gcmd-keywords

e.g. `ATMOSPHERIC OZONE`

https://gcmd.earthdata.nasa.gov/KeywordViewer/scheme/all/dd316647-9043-40c3-9329-f22f9215fefa

> ATMOSPHERIC OZONE
>
> Full Path EARTH SCIENCEATMOSPHEREATMOSPHERIC CHEMISTRYOXYGEN COMPOUNDSATMOSPHERIC OZONE
>
> UUID dd316647-9043-40c3-9329-f22f9215fefa
>
> Category Earth Science
>
> [Earthdata Search Client](https://search.earthdata.nasa.gov/portal/idn/search?fst0=ATMOSPHERE&fsm0=ATMOSPHERIC+CHEMISTRY&fs10=OXYGEN+COMPOUNDS&fs20=ATMOSPHERIC+OZONE)
>
> Definition
>
> Atmospheric Ozone is one of the most important trace gases in our atmosphere that both benefits and harms life on Earth. High ground-level ozone amounts contribute to poor air quality, adversely affecting human health, agricultural productivity, and forested ecosystems. Ozone absorbs infrared radiation, and is most potent as a greenhouse gas in the cold upper troposphere located 8–15 km above the surface. In the stratosphere, between approximately 15 and 50 km above the Earth’s surface, a layer rich in ozone serves as a “sunscreen” for the world by shielding the Earth’s surface from harmful ultraviolet radiation. This absorption of solar energy also affects atmospheric circulation patterns and thus influences weather around the globe. Moreover, throughout the atmosphere, ozone is the key ingredient that initiates chemical cleansing of the atmosphere of various pollutants, such as carbon monoxide and methane, among others, which could otherwise accumulate to harmful levels or exert a stronger influence on climate. Therefore, changes to ozone anywhere in the atmosphere can have major impacts on the Earth.
>
> Reference
https://www.ametsoc.org/index.cfm/ams/about-ams/ams-statements/statements-of-the-ams-in-force/atmospheric-ozone1/
>
> Broader OXYGEN COMPOUNDS
>
> Narrower OZONE PROFILESOZONE SURFACETOTAL OZONE

**Comment by m-mohr** [comment]
Following OGC API - Records now, keywords is the free-form equivalent in STAC, see the corresponding PR in stac-spec.
