### ISSUE TITLE
Access to the ontology datasets

### ISSUE THREAD

**Issue by schwehr** [stac-extensions/themes#3]
What are the licenses to the suggested datasets and are they easy to access?

geonames appears to have pay and free tiers.  The free tier appears confusing.  There are many tab delimited files.  

My take:  If the extension recommends some dataset, I think is should be as easily accessible to as many people as possible.  This might mean providing a couple line demo of how to get the data and listing the license (pref CC0 or CC-BY; prefer not SA; definitely no NC... to maximize adoption).  Or it might mean providing a reprocessed dataset in something that users can pass through ogr2ogr to get whatever format they desire.

https://spdx.org/licenses/

**Comment by m-mohr** [comment]
Sorry, I'm not sure how this relates to the extension. The databases are just examples.
