### ISSUE TITLE
Alignment with OGC API - Records?

### ISSUE THREAD

**Issue by m-mohr** [stac-extensions/themes#4]
Should we align this with what OGC API - Records does? They have something called `themes` which looks very similar: 
https://github.com/opengeospatial/ogcapi-records/search?q=themes

**Comment by emmanuelmathot** [comment]
maybe we should. Let me sync with all the discussions around. I will give a feedback soon.

**Comment by emmanuelmathot** [comment]
the idea is indeed very similar. In this [doc](https://github.com/opengeospatial/ogcapi-records/blob/bb1f828568293dfbbd7b1651cb85fa1c0aaebb80/core/standard/recommendations/record-core/REC_record-keywords-themes.adoc), we see 2 concepts:
- free `keywords`
- `themes` framed by a lexical system

In the initial proposal, I called it terms but themes is fine with me and I think an alignment could be beneficial

**Comment by m-mohr** [comment]
Indeed, keywords is aligned with STAC Collections and will (hopefully) stay as it is. I'm not sure whether they've settled on the name "themes" yet...

**Comment by m-mohr** [comment]
Done in main, please review :-)
